service: gym-mates
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1
  memorySize: 256
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'
functions:
  registerSubscriptions:
    handler: lambda.registerSubscriptions
    events:
      - httpApi:
          path: /register-subscriptions
          method: POST
